import { ActivityIndicator, Pressable, StyleSheet, Text, View, ViewProps } from "react-native";
import type { ReactNode } from "react";

export function Card({ children, className, ...props }: ViewProps & { className?: string }) { return <View {...props} className={`rounded-3xl border border-border bg-surface p-4 ${className ?? ""}`}>{children}</View>; }
export function Button({ title, onPress, variant = "primary", disabled = false, compact = false }: { title: string; onPress: () => void; variant?: "primary" | "secondary" | "danger"; disabled?: boolean; compact?: boolean }) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.button, styles[variant], compact && styles.compact, (pressed || disabled) && styles.pressed]}><Text style={[styles.label, styles[`${variant}Label` as const], compact && styles.compactLabel]}>{title}</Text></Pressable>; }
export function SectionHeader({ title, action, onAction }: { title: string; action?: string; onAction?: () => void }) { return <View className="mb-3 flex-row items-center justify-between"><Text className="text-lg font-bold text-foreground">{title}</Text>{action && onAction ? <Pressable onPress={onAction} accessibilityRole="button" style={({ pressed }) => pressed && styles.textPressed}><Text className="text-sm font-bold text-primary">{action}</Text></Pressable> : null}</View>; }
export function Metric({ label, value, tone = "default", helper }: { label: string; value: string; tone?: "default" | "positive" | "negative" | "warning"; helper?: string }) { const colors = { default: "text-foreground", positive: "text-success", negative: "text-error", warning: "text-warning" }; return <View className="min-w-[45%] flex-1 gap-1"><Text className="text-xs font-medium text-muted">{label}</Text><Text numberOfLines={1} className={`text-base font-bold ${colors[tone]}`}>{value}</Text>{helper ? <Text numberOfLines={1} className="text-[11px] text-muted">{helper}</Text> : null}</View>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <Card className="items-center gap-3 py-8"><View className="h-12 w-12 items-center justify-center rounded-2xl bg-primary/10"><Text className="text-xl font-bold text-primary">+</Text></View><Text className="text-center text-base font-bold text-foreground">{title}</Text><Text className="max-w-[280px] text-center text-sm leading-5 text-muted">{description}</Text>{action}</Card>; }
export function LoadingState() { return <View className="flex-1 items-center justify-center gap-3 bg-background"><ActivityIndicator color="#0B5D4C" /><Text className="text-sm text-muted">Carregando sua carteira…</Text></View>; }
const styles = StyleSheet.create({ button: { alignItems: "center", borderRadius: 16, justifyContent: "center", minHeight: 50, paddingHorizontal: 18 }, compact: { minHeight: 40, borderRadius: 12, paddingHorizontal: 14 }, primary: { backgroundColor: "#0B5D4C" }, secondary: { backgroundColor: "#DFF4ED" }, danger: { backgroundColor: "#FBE9E6" }, pressed: { opacity: 0.74, transform: [{ scale: 0.98 }] }, label: { fontSize: 15, fontWeight: "700" }, compactLabel: { fontSize: 13 }, primaryLabel: { color: "#FFFFFF" }, secondaryLabel: { color: "#0B5D4C" }, dangerLabel: { color: "#B44332" }, textPressed: { opacity: 0.6 } });
