import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";
import { Platform } from "react-native";
import { PortfolioData } from "./portfolio";
export type Backup = { format: "fii-guard-backup"; version: 1; exportedAt: string; operations: PortfolioData["operations"]; dividends: PortfolioData["dividends"]; quotes: PortfolioData["quotes"] };
export function createBackup(data: PortfolioData): Backup { return { format: "fii-guard-backup", version: 1, exportedAt: new Date().toISOString(), operations: data.operations, dividends: data.dividends, quotes: data.quotes }; }
export async function exportBackup(data: PortfolioData) { if (Platform.OS === "web") throw new Error("Backup de arquivo está disponível no aplicativo Android."); if (!FileSystem.documentDirectory) throw new Error("Armazenamento local indisponível."); const uri = `${FileSystem.documentDirectory}fii-guard-backup-${new Date().toISOString().slice(0, 10)}.json`; await FileSystem.writeAsStringAsync(uri, JSON.stringify(createBackup(data), null, 2), { encoding: FileSystem.EncodingType.UTF8 }); if (!(await Sharing.isAvailableAsync())) throw new Error("Compartilhamento indisponível neste dispositivo."); await Sharing.shareAsync(uri, { mimeType: "application/json", dialogTitle: "Salvar backup da carteira" }); }
export async function importBackup(): Promise<Backup | null> { const result = await DocumentPicker.getDocumentAsync({ type: ["application/json", "text/json", "text/plain"], copyToCacheDirectory: true, multiple: false }); if (result.canceled || !result.assets?.[0]) return null; const raw = await FileSystem.readAsStringAsync(result.assets[0].uri, { encoding: FileSystem.EncodingType.UTF8 }); let value: unknown; try { value = JSON.parse(raw); } catch { throw new Error("O arquivo não contém um JSON válido."); } if (!value || typeof value !== "object" || (value as any).format !== "fii-guard-backup" || (value as any).version !== 1 || !Array.isArray((value as any).operations) || !Array.isArray((value as any).dividends)) throw new Error("Backup incompatível com o FII Guard."); return value as Backup; }
