export type CalculationOperation = { id: string; ticker: string; kind: "buy" | "sell"; date: string; quantity: number; price: number; fees: number; createdAt: string };
export type CalculationDividend = { ticker: string; paymentDate: string; dateCom?: string; amountPerShare: number; kind: "income" | "amortization" };
export type CalculationPosition = { ticker: string; quantity: number; costBasis: number; averagePrice: number; realizedResult: number };
const tickerOf = (value: string) => value.trim().toUpperCase().replace(/[^A-Z0-9]/g, "").replace(/SA$/, "");
const ordered = (items: CalculationOperation[]) => [...items].sort((a, b) => a.date.localeCompare(b.date) || a.createdAt.localeCompare(b.createdAt));
export function calculatePositions(operations: CalculationOperation[], _quotes?: Record<string, number>): CalculationPosition[] { const map = new Map<string, CalculationPosition>(); for (const op of ordered(operations)) { const ticker = tickerOf(op.ticker); const p = map.get(ticker) ?? { ticker, quantity: 0, costBasis: 0, averagePrice: 0, realizedResult: 0 }; const gross = op.quantity * op.price; if (op.kind === "buy") { p.costBasis += gross + op.fees; p.quantity += op.quantity; p.averagePrice = p.quantity ? p.costBasis / p.quantity : 0; } else { const average = p.quantity ? p.costBasis / p.quantity : 0; p.realizedResult += gross - op.fees - average * op.quantity; p.costBasis = Math.max(0, p.costBasis - average * op.quantity); p.quantity = Math.max(0, p.quantity - op.quantity); p.averagePrice = p.quantity ? p.costBasis / p.quantity : 0; } map.set(ticker, p); } return [...map.values()]; }
export function quantityAt(operations: CalculationOperation[], ticker: string, date: string) { return calculatePositions(operations.filter((op) => op.date <= date)).find((p) => p.ticker === tickerOf(ticker))?.quantity ?? 0; }
export function dividendValue(dividend: CalculationDividend, operations: CalculationOperation[]) { return dividend.amountPerShare * quantityAt(operations, dividend.ticker, dividend.dateCom || dividend.paymentDate); }
export function monthReport(operations: CalculationOperation[], dividends: CalculationDividend[], key: string) { const [year, month] = key.split("-").map(Number); const start = `${key}-01`; const end = new Date(Date.UTC(year, month, 0)).toISOString().slice(0, 10); const period = operations.filter((op) => op.date >= start && op.date <= end); const before = calculatePositions(operations.filter((op) => op.date < start)); const through = calculatePositions(operations.filter((op) => op.date <= end)); const realizedResult = through.reduce((s, p) => s + p.realizedResult, 0) - before.reduce((s, p) => s + p.realizedResult, 0); const incomeTotal = dividends.filter((d) => d.paymentDate >= start && d.paymentDate <= end && d.kind === "income").reduce((s, d) => s + dividendValue(d, operations), 0); const amortizationTotal = dividends.filter((d) => d.paymentDate >= start && d.paymentDate <= end && d.kind === "amortization").reduce((s, d) => s + dividendValue(d, operations), 0); return { purchaseTotal: period.filter((op) => op.kind === "buy").reduce((s, op) => s + op.quantity * op.price + op.fees, 0), saleTotal: period.filter((op) => op.kind === "sell").reduce((s, op) => s + op.quantity * op.price - op.fees, 0), incomeTotal, amortizationTotal, realizedResult, movementCount: period.length }; }
