import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import Svg, { Path, Text as SvgText } from "react-native-svg";
import { useMemo } from "react";
import { usePortfolio } from "@/lib/portfolio";
import { findFund } from "@/lib/fii-catalog";
import { ScreenContainer } from "@/components/screen-container";
import { Button, EmptyState, LoadingState } from "@/components/portfolio-ui";
import { currency, number } from "@/lib/format";

const COLORS = ["#26D39A", "#FFBC3B", "#2DA9E2", "#FF6B78", "#A982E8", "#2BC6C5", "#8BC34A", "#E7A477", "#8C7CF0", "#F18AAB"];
type Slice = { label: string; value: number };
function polar(cx: number, cy: number, radius: number, angle: number) { return { x: cx + Math.cos(angle) * radius, y: cy + Math.sin(angle) * radius }; }
function Donut({ title, slices, total }: { title: string; slices: Slice[]; total: number }) {
  const safeTotal = total || 1; const radius = 78; const cx = 150; const cy = 128; let angle = -Math.PI / 2; const items = slices.map((slice, index) => { const start = angle; const end = angle + slice.value / safeTotal * Math.PI * 2; angle = end; const mid = (start + end) / 2; const large = end - start > Math.PI ? 1 : 0; const a = polar(cx, cy, radius, start); const b = polar(cx, cy, radius, end); const outer = polar(cx, cy, radius + 5, mid); const internal = polar(cx, cy, radius * 0.58, mid); return { slice, index, start, end, mid, large, a, b, outer, internal, small: slice.value / safeTotal < 0.075 }; });
  const smallItems = items.filter((item) => item.small); const left = smallItems.filter((item) => Math.cos(item.mid) < 0).sort((a, b) => a.outer.y - b.outer.y); const right = smallItems.filter((item) => Math.cos(item.mid) >= 0).sort((a, b) => a.outer.y - b.outer.y); const place = (side: typeof left) => side.map((item, index) => ({ ...item, labelY: 55 + index * 25 })); const placed = [...place(left), ...place(right)];
  return <View style={styles.card}><Text style={styles.cardTitle}>{title}</Text><View style={styles.pieWrap}><Svg width={300} height={270} viewBox="0 0 300 270">{items.map((item) => <Path key={`${item.slice.label}-${item.index}`} d={`M ${cx} ${cy} L ${item.a.x} ${item.a.y} A ${radius} ${radius} 0 ${item.large} 1 ${item.b.x} ${item.b.y} Z`} fill={COLORS[item.index % COLORS.length]} stroke="#17232C" strokeWidth="2" />)}{items.filter((item) => !item.small).map((item) => <SvgText key={`inside-${item.slice.label}-${item.index}`} x={item.internal.x} y={item.internal.y} fill="#071219" fontSize="10" fontWeight="800" textAnchor="middle">{`${item.slice.label} ${((item.slice.value / safeTotal) * 100).toFixed(1)}%`}</SvgText>)}{placed.map((item) => { const elbowX = Math.cos(item.mid) < 0 ? 38 : 262; const endX = Math.cos(item.mid) < 0 ? 5 : 295; return <Path key={`callout-${item.slice.label}-${item.index}`} d={`M ${item.outer.x} ${item.outer.y} L ${elbowX} ${item.labelY} L ${endX} ${item.labelY}`} fill="none" stroke="#0B1115" strokeWidth="2" />; })}</Svg>{placed.map((item) => <View key={`outside-${item.slice.label}-${item.index}`} style={[styles.pieCallout, { left: Math.cos(item.mid) < 0 ? 3 : 264, top: item.labelY - 10 }]}><View style={[styles.calloutDot, { backgroundColor: COLORS[item.index % COLORS.length] }]} /><Text style={styles.calloutText} numberOfLines={1}>{item.slice.label} {((item.slice.value / safeTotal) * 100).toFixed(1)}%</Text></View>)}<View style={styles.pieTotal}><Text style={styles.centerLabel}>Total</Text><Text style={styles.centerValue}>{currency(total)}</Text></View></View><View style={styles.legend}>{slices.map((slice, index) => <View key={`legend-${slice.label}-${index}`} style={styles.legendRow}><View style={[styles.dot, { backgroundColor: COLORS[index % COLORS.length] }]} /><Text style={styles.legendName} numberOfLines={1}>{slice.label}</Text><Text style={styles.legendMoney}>{currency(slice.value)}</Text><Text style={styles.legendPercent}>{(slice.value / safeTotal * 100).toFixed(1)}%</Text></View>)}</View></View>;
}
export default function PortfolioScreen() {
  const { ready, snapshot } = usePortfolio();
  const positions = snapshot.active;
  const total = positions.reduce((sum, item) => sum + (item.marketValue ?? item.costBasis), 0);
  const assetSlices = positions.map((item) => ({ label: item.ticker, value: item.marketValue ?? item.costBasis })).sort((a, b) => b.value - a.value);
  const groupSlices = (field: "sector" | "segment") => { const map = new Map<string, number>(); positions.forEach((item) => { const fund = findFund(item.ticker); const label = (field === "sector" ? fund?.sector : fund?.segment) || "Outros"; map.set(label, (map.get(label) || 0) + (item.marketValue ?? item.costBasis)); }); return [...map].map(([label, value]) => ({ label, value })).sort((a, b) => b.value - a.value); }; const sectorSlices = useMemo(() => groupSlices("sector"), [positions]); const segmentSlices = useMemo(() => groupSlices("segment"), [positions]);
  if (!ready) return <LoadingState />;
  return <ScreenContainer style={styles.screen} edges={["top", "left", "right"]}><FlatList data={positions} keyExtractor={(item) => item.ticker} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} ListHeaderComponent={<View><View style={styles.header}><View style={styles.brand}><View style={styles.brandIcon}><Text style={styles.brandGlyph}>▥</Text></View><Text style={styles.brandTitle}>Carteira FIIs</Text></View><Pressable onPress={() => router.push("/settings" as any)}><Text style={styles.exit}>↪ Sair</Text></Pressable></View><Donut title="Peso por ativo" slices={assetSlices} total={total} /><Donut title="Peso por setor" slices={sectorSlices} total={total} /><Donut title="Peso por segmento" slices={segmentSlices} total={total} /><Text style={styles.sectionTitle}>Ativos</Text></View>} renderItem={({ item }) => { const fund = findFund(item.ticker); const sector = fund?.sector || "Outros"; const segment = fund?.segment || "Outros"; return <Pressable onPress={() => router.push(`/fund/${item.ticker}` as any)} style={({ pressed }) => [styles.assetRow, pressed && styles.pressed]}><View style={styles.assetLeft}><Text style={styles.ticker}>{item.ticker}</Text><Text style={styles.sub}>{number(item.quantity, 0)} cotas · PM {currency(item.averagePrice)} · atual {currency(item.lastPrice)}</Text><Text style={item.unrealizedResult !== undefined && item.unrealizedResult < 0 ? styles.loss : styles.gain}>↗ {currency(item.unrealizedResult, { sign: true })}</Text></View><View style={styles.assetRight}><Text style={styles.market}>{currency(item.marketValue)}</Text><Text style={styles.sector}>{sector} · {segment}</Text></View></Pressable>}} ListEmptyComponent={<EmptyState title="Nenhuma posição ativa" description="Registre uma compra para começar a acompanhar a carteira." action={<Button title="Registrar compra" onPress={() => router.push("/transaction-form" as any)} />} />} /></ScreenContainer>;
}
const styles = StyleSheet.create({ screen: { backgroundColor: "#071219" }, content: { paddingBottom: 30 }, header: { alignItems: "center", borderBottomColor: "#1D2A32", borderBottomWidth: 1, flexDirection: "row", justifyContent: "space-between", marginHorizontal: -20, paddingHorizontal: 30, paddingBottom: 20, paddingTop: 16 }, brand: { alignItems: "center", flexDirection: "row", gap: 14 }, brandIcon: { alignItems: "center", backgroundColor: "#063F39", borderRadius: 24, height: 48, justifyContent: "center", width: 48 }, brandGlyph: { color: "#26D39A", fontSize: 25 }, brandTitle: { color: "#F4F7F8", fontSize: 22, fontWeight: "800" }, exit: { color: "#9AA7AF", fontSize: 16 }, card: { backgroundColor: "#17232C", borderColor: "#293943", borderRadius: 30, borderWidth: 1, marginTop: 18, padding: 28 }, cardTitle: { color: "#AAB6BE", fontSize: 21, fontWeight: "700" }, pieWrap: { alignItems: "center", height: 270, justifyContent: "center", position: "relative" }, pieTotal: { alignItems: "center", position: "absolute", top: 108, width: 300 }, pieCallout: { alignItems: "center", flexDirection: "row", maxWidth: 35, position: "absolute" }, calloutDot: { borderRadius: 4, height: 8, marginRight: 3, width: 8 }, calloutText: { color: "#DCE5E8", fontSize: 8, fontWeight: "700" }, donutCenter: { alignItems: "center", position: "absolute" }, centerLabel: { color: "#87949D", fontSize: 16 }, centerValue: { color: "#F5F7F8", fontSize: 21, fontWeight: "800", marginTop: 5 }, legend: { gap: 10 }, legendRow: { alignItems: "center", flexDirection: "row" }, dot: { borderRadius: 8, height: 16, marginRight: 12, width: 16 }, legendName: { color: "#EDF2F4", flex: 1, fontSize: 16 }, legendMoney: { color: "#AAB6BE", fontSize: 15, marginRight: 15 }, legendPercent: { color: "#F4F7F8", fontSize: 16, fontWeight: "800", width: 48 }, sectionTitle: { color: "#F4F7F8", fontSize: 24, fontWeight: "800", marginBottom: 10, marginTop: 26 }, assetRow: { backgroundColor: "#17232C", borderBottomColor: "#293943", borderBottomWidth: 1, flexDirection: "row", justifyContent: "space-between", padding: 18 }, assetLeft: { flex: 1 }, assetRight: { alignItems: "flex-end", justifyContent: "center" }, ticker: { color: "#EEF4F5", fontSize: 18, fontWeight: "800" }, sub: { color: "#9AA7AF", fontSize: 13, marginTop: 7 }, sector: { color: "#84939C", fontSize: 13, marginTop: 7 }, market: { color: "#F4F7F8", fontSize: 18, fontWeight: "800" }, gain: { color: "#26D39A", fontSize: 14, marginTop: 8 }, loss: { color: "#FF6B78", fontSize: 14, marginTop: 8 }, pressed: { opacity: 0.7 } });
