import { Pressable, StyleSheet, Text, View } from "react-native";
import { useState } from "react";
import { usePortfolio, monthReport, yearReport } from "@/lib/portfolio";
import { ScreenContainer } from "@/components/screen-container";
import { Card, LoadingState, Metric, SectionHeader } from "@/components/portfolio-ui";
import { currency, monthLabel } from "@/lib/format";
const shift = (key: string, delta: number) => { const [year, month] = key.split("-").map(Number); return new Date(Date.UTC(year, month - 1 + delta, 1)).toISOString().slice(0, 7); };
export default function ReportsScreen() { const { ready, operations, dividends } = usePortfolio(); const [selected, setSelected] = useState(new Date().toISOString().slice(0, 7)); if (!ready) return <LoadingState />; const report = monthReport(operations, dividends, selected); const annual = yearReport(operations, dividends, selected.slice(0, 4)); return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><View className="flex-1 pt-2"><Text className="text-sm font-medium text-muted">Histórico calculado</Text><Text className="mt-1 text-3xl font-bold text-foreground">Resultados</Text><View className="my-6 flex-row items-center justify-between rounded-2xl border border-border bg-surface p-2"><Pressable onPress={() => setSelected(shift(selected, -1))} style={styles.period}><Text className="text-xl text-primary">‹</Text></Pressable><Text className="text-base font-bold capitalize text-foreground">{monthLabel(selected)}</Text><Pressable onPress={() => setSelected(shift(selected, 1))} style={styles.period}><Text className="text-xl text-primary">›</Text></Pressable></View><Card className="mb-5 bg-primary"><Text className="text-sm text-white/75">Fluxo líquido do mês</Text><Text className="mt-1 text-3xl font-bold text-white">{currency(report.netCashFlow, { sign: true })}</Text><Text className="mt-3 text-xs text-white/70">Aportes, vendas e proventos do período.</Text></Card><SectionHeader title="Resumo mensal" /><Card className="mb-5"><View className="flex-row gap-4"><Metric label="Aportes" value={currency(report.purchaseTotal)} /><Metric label="Vendas líquidas" value={currency(report.saleTotal)} /></View><View className="mt-5 flex-row gap-4 border-t border-border pt-4"><Metric label="Rendimentos" value={currency(report.incomeTotal)} tone="positive" /><Metric label="Amortizações" value={currency(report.amortizationTotal)} tone="warning" /></View><View className="mt-5 border-t border-border pt-4"><Metric label="Resultado realizado" value={currency(report.realizedResult, { sign: true })} tone={report.realizedResult >= 0 ? "positive" : "negative"} helper={`${report.movementCount} movimentações`} /></View></Card><SectionHeader title={`Acumulado em ${selected.slice(0, 4)}`} /><Card><View className="flex-row gap-4"><Metric label="Rendimentos" value={currency(annual.incomeTotal)} tone="positive" /><Metric label="Resultado realizado" value={currency(annual.realizedResult, { sign: true })} tone={annual.realizedResult >= 0 ? "positive" : "negative"} /></View></Card><Text className="mt-5 text-center text-xs leading-5 text-muted">A virada de mês e ano é automática, baseada na data dos seus lançamentos.</Text></View></ScreenContainer>; }
const styles = StyleSheet.create({ period: { alignItems: "center", borderRadius: 14, height: 38, justifyContent: "center", width: 38 } });
